from __future__ import annotations

from enum import StrEnum


class DomainErrorCode(StrEnum):
    CONTRACT_VIOLATION = "CORE_CONTRACT_VIOLATION"
    DIGEST_MISMATCH = "CORE_COMMAND_DIGEST_MISMATCH"
    SECURITY_BINDING_MISMATCH = "CORE_SECURITY_BINDING_MISMATCH"
    INVALID_STATE = "CORE_INVALID_TASK_STATE"
    INVALID_TRANSITION = "CORE_INVALID_STATE_TRANSITION"
    APPROVAL_BINDING_MISMATCH = "CORE_APPROVAL_BINDING_MISMATCH"
    KNOWLEDGE_CONTENT_HASH_MISMATCH = "CORE_KNOWLEDGE_CONTENT_HASH_MISMATCH"
    KNOWLEDGE_SOURCE_DIGEST_MISMATCH = "CORE_KNOWLEDGE_SOURCE_DIGEST_MISMATCH"
    KNOWLEDGE_INVALID_STATE = "CORE_KNOWLEDGE_INVALID_STATE"
    KNOWLEDGE_VERSION_CONFLICT = "CORE_KNOWLEDGE_VERSION_CONFLICT"
    KNOWLEDGE_REFERENCE_MISMATCH = "CORE_KNOWLEDGE_REFERENCE_MISMATCH"


class DomainViolation(ValueError):
    """A deterministic domain rejection with a stable, non-sensitive code."""

    def __init__(self, code: DomainErrorCode, safe_message: str) -> None:
        super().__init__(safe_message)
        self.code = code
        self.safe_message = safe_message
