from __future__ import annotations

from enum import StrEnum


class GatewayReason(StrEnum):
    REQUEST_ACCEPTED = "GATEWAY_REQUEST_ACCEPTED"
    IDENTITY_VERIFIED = "GATEWAY_IDENTITY_VERIFIED"
    TOOL_ALLOWED = "GATEWAY_TOOL_ALLOWED"
    POLICY_ALLOWED = "GATEWAY_POLICY_ALLOWED"
    APPROVAL_NOT_REQUIRED = "GATEWAY_APPROVAL_NOT_REQUIRED"
    APPROVAL_BOUND = "GATEWAY_APPROVAL_BOUND"
    LEDGER_PREPARED = "GATEWAY_LEDGER_PREPARED"
    LEDGER_REPLAY = "GATEWAY_LEDGER_REPLAY"
    UPSTREAM_STARTED = "GATEWAY_UPSTREAM_STARTED"
    UPSTREAM_SUCCEEDED = "GATEWAY_UPSTREAM_SUCCEEDED"
    READBACK_VERIFIED = "GATEWAY_READBACK_VERIFIED"
    RESULT_VERIFIED = "GATEWAY_RESULT_VERIFIED"
    RESULT_FAILED = "GATEWAY_RESULT_FAILED"
    RESULT_UNKNOWN = "GATEWAY_RESULT_UNKNOWN"
    RECONCILIATION_PENDING = "GATEWAY_RECONCILIATION_PENDING"
    RECONCILIATION_VERIFIED = "GATEWAY_RECONCILIATION_VERIFIED"
    CONFIRMED_NOT_EXECUTED = "GATEWAY_CONFIRMED_NOT_EXECUTED"
    SIGNAL_RETAINED = "GATEWAY_SIGNAL_RETAINED"
    TOOL_NOT_REGISTERED = "PLATFORM_TOOL_NOT_REGISTERED"
    TOOL_NOT_ALLOWED = "PLATFORM_TOOL_NOT_ALLOWED"
    TOOL_SCHEMA_MISMATCH = "PLATFORM_TOOL_SCHEMA_HASH_MISMATCH"
    TOOL_INPUT_INVALID = "PLATFORM_TOOL_INPUT_INVALID"
    TOOL_OUTPUT_INVALID = "PLATFORM_TOOL_OUTPUT_INVALID"
    POLICY_UNAVAILABLE = "PLATFORM_POLICY_UNAVAILABLE"
    APPROVAL_UNAVAILABLE = "PLATFORM_APPROVAL_UNAVAILABLE"
    LEDGER_UNAVAILABLE = "PLATFORM_LEDGER_UNAVAILABLE"
    SIGNAL_UNAVAILABLE = "PLATFORM_SIGNAL_UNAVAILABLE"
    IDEMPOTENCY_CONFLICT = "PLATFORM_IDEMPOTENCY_CONFLICT"
    UPSTREAM_NOT_SENT = "PLATFORM_UPSTREAM_NOT_SENT"
    UPSTREAM_UNAVAILABLE = "PLATFORM_UPSTREAM_UNAVAILABLE"
    UPSTREAM_OUTCOME_UNKNOWN = "PLATFORM_UPSTREAM_OUTCOME_UNKNOWN"
    UPSTREAM_REJECTED = "PLATFORM_UPSTREAM_REJECTED"
    READBACK_MISMATCH = "PLATFORM_READBACK_MISMATCH"
    RECONCILIATION_REQUIRED = "PLATFORM_RECONCILIATION_REQUIRED"
    RECONCILIATION_UNAVAILABLE = "PLATFORM_RECONCILIATION_UNAVAILABLE"


class GatewayAdapterDisposition(StrEnum):
    NOT_SENT = "not_sent"
    OUTCOME_UNKNOWN = "outcome_unknown"
    REJECTED = "rejected"


class GatewayAdapterError(RuntimeError):
    def __init__(
        self,
        disposition: GatewayAdapterDisposition,
        safe_code: str,
        safe_message: str,
    ) -> None:
        super().__init__(safe_message)
        self.disposition = disposition
        self.safe_code = safe_code
        self.safe_message = safe_message


class GatewayControlError(RuntimeError):
    def __init__(self, code: str, safe_message: str) -> None:
        super().__init__(safe_message)
        self.code = code
        self.safe_message = safe_message
