from __future__ import annotations

from enum import StrEnum


class SecurityErrorCode(StrEnum):
    CONTEXT_UNAVAILABLE = "PLATFORM_SECURITY_CONTEXT_UNAVAILABLE"
    CONTEXT_UNTRUSTED = "PLATFORM_SECURITY_CONTEXT_UNTRUSTED"
    CONTEXT_EXPIRED = "PLATFORM_SECURITY_CONTEXT_EXPIRED"
    CONTEXT_NOT_ACTIVE = "PLATFORM_SECURITY_CONTEXT_NOT_ACTIVE"
    TENANT_MISMATCH = "PLATFORM_TENANT_MISMATCH"
    PURPOSE_DENIED = "PLATFORM_PURPOSE_DENIED"
    WORKLOAD_UNTRUSTED = "PLATFORM_WORKLOAD_UNTRUSTED"
    WORKLOAD_EXPIRED = "PLATFORM_WORKLOAD_EXPIRED"
    AGENT_MISMATCH = "PLATFORM_AGENT_MISMATCH"
    AUDIENCE_MISMATCH = "PLATFORM_AUDIENCE_MISMATCH"
    TOOL_SCOPE_DENIED = "PLATFORM_TOOL_SCOPE_DENIED"
    CREDENTIAL_UNAVAILABLE = "PLATFORM_CREDENTIAL_UNAVAILABLE"
    UNSAFE_PROJECTION = "PLATFORM_UNSAFE_PROJECTION"
    IDENTITY_TOKEN_INVALID = "PLATFORM_IDENTITY_TOKEN_INVALID"
    IDENTITY_CLAIMS_INVALID = "PLATFORM_IDENTITY_CLAIMS_INVALID"
    IDENTITY_SOURCE_UNAVAILABLE = "PLATFORM_IDENTITY_SOURCE_UNAVAILABLE"
    IDENTITY_MAPPING_DENIED = "PLATFORM_IDENTITY_MAPPING_DENIED"
    IDENTITY_EXPIRED = "PLATFORM_IDENTITY_EXPIRED"
    NONCE_REPLAY = "PLATFORM_IDENTITY_NONCE_REPLAY"
    USER_TOKEN_FORBIDDEN = "PLATFORM_USER_TOKEN_FORBIDDEN"


class SecurityError(RuntimeError):
    def __init__(self, code: SecurityErrorCode, safe_message: str) -> None:
        super().__init__(safe_message)
        self.code = code
        self.safe_message = safe_message
